### ISSUE TITLE
Create main character placeholder with full set of animations

### ISSUE THREAD

**Issue by vamjan** [vamjan/Wolfpack-project#19]

**Comment by Zahry** [comment]
First iteration of 4way sprites for animation of main char. Not a total placeholder, but base for future work.
![mainchar_back](https://cloud.githubusercontent.com/assets/17437479/13666885/19a33fc2-e6b4-11e5-8cf8-b3f3926638cf.png)
![mainchar_front](https://cloud.githubusercontent.com/assets/17437479/13666886/19a42d38-e6b4-11e5-94a0-ae0aae444041.png)
![mainchar_left](https://cloud.githubusercontent.com/assets/17437479/13666887/19a4f786-e6b4-11e5-83db-3983391f55a0.png)
![mainchar_right](https://cloud.githubusercontent.com/assets/17437479/13666888/19a8f1ec-e6b4-11e5-8de8-5d5d13ec81b3.png)
