### ISSUE TITLE
Border map assets

### ISSUE THREAD

**Issue by vamjan** [vamjan/Wolfpack-project#5]
Forests, cliffs etc.

**Comment by Zahry** [comment]
Finished with some placeholders for now 
![cliff_x](https://cloud.githubusercontent.com/assets/17437479/13329910/cf517afa-dbf6-11e5-90db-5d73908782fe.png)
![cliff_y](https://cloud.githubusercontent.com/assets/17437479/13329911/cf55ed4c-dbf6-11e5-8143-f7922270acfb.png)
