### ISSUE TITLE
Concept art for main character

### ISSUE THREAD

**Issue by vamjan** [vamjan/Wolfpack-project#6]
self explanatory

**Comment by Zahry** [comment]
First sketch:
![img_20160224_215113](https://cloud.githubusercontent.com/assets/17437479/13302354/be9f5df6-db49-11e5-8b8f-f9219c107eb6.jpg)
and with some colorizing to show color scheme:
![ona1](https://cloud.githubusercontent.com/assets/17437479/13302355/be9f8830-db49-11e5-87d1-82b6c8411a01.jpg)

**Comment by Zahry** [comment]
Second sketch, just imagine the colors :)
![2 concept - her 3](https://cloud.githubusercontent.com/assets/17437479/13334364/ec5debf0-dc0b-11e5-9f09-9c461442369b.jpg)
